Repository SOPT-all/36-SOPKATHON-WEB-WEB3, pull requests merged in 2025-05, with the labels that each got.

#5 [Init] - prettier, eslint 세팅
  .eslintrc.cjs
  .gitignore
  .prettierrc
  .yarn/install-state.gz
  .yarnnrc.yml
  .yarnrc.yml
  eslint.config.js
  package.json
  yarn.lock
Labels: setting, 채은

#4 [Init] - 스타일 설정
  package.json
  src/App.jsx
  src/main.jsx
  src/shared/styles/.gitignore
  src/shared/styles/font.css
  src/shared/styles/globalStyle.jsx
  src/shared/styles/theme.js
Labels: setting, 혜린

#17 [Init] - svgr 세팅
  .eslintrc.cjs
  package.json
  src/shared/assets/Vite.jsx
  src/shared/assets/index.jsx
  vite.config.js
  yarn.lock
Labels: setting, 채은

#27 Feat: 헤더 컴포넌트 생성
  public/icon_back.svg
  src/shared/assets/IconBack.jsx
  src/shared/assets/index.jsx
  src/shared/components/Layout/Header.jsx
  src/shared/components/Layout/index.jsx
  src/shared/routes/pageRoutes.jsx
Labels: feat, 새봄

#25 [Feat] - 카드 컴포넌트 구현
  public/Profile.svg
  public/icon-clock.svg
  src/shared/assets/IconClock.jsx
  src/shared/assets/Profile.jsx
  src/shared/assets/index.jsx
  src/shared/components/Card.jsx
  src/shared/styles/theme.js
Labels: feat, 채은

#28 [Feat] - 필터링 버튼 컴포넌트 구현
  src/shared/components/filter-button/FilterButton.jsx
  src/shared/styles/theme.js
Labels: feat, 채은

#34 Setting: Axios 기본 세팅
  .env
  src/shared/apis/apiClient.js
  src/shared/apis/apis.js
Labels: setting, 지성

#39 Fix: vercel 404 오류 해결
  vercel.json
Labels: fix, 지성

#45 feat: farm detail api 구현
  .gitignore
  src/pages/farmDetail/components/DetailBody.jsx
  src/pages/farmDetail/components/DetailContent.jsx
  src/pages/farmDetail/components/LaborPrize.jsx
  src/pages/farmDetail/components/ReviewList.jsx
  src/pages/farmDetail/page/FarmDetail.jsx
Labels: feat, 혜린

#46 Feat: 지하철 리스트 api 연동
  src/main.jsx
  src/pages/Search/SearchPage.jsx
Labels: feat, 지성
